#!/usr/bin/env bash
set -euo pipefail

export BIN=${BIN-bin}

./scripts/reformat.sh
make -j`nproc`
./tests/run $BIN

lines=$(find $BIN -name "*.lines" | xargs cat | awk '{s+=$1} END {printf "%d\n", (s/1000)}')
echo "compilation mass: $lines kloc"
