#!/usr/bin/env bash
set -euo pipefail

export BIN=${BIN-bin}

if [ $(uname -s) == "Darwin" ]; then
  CORES=$(sysctl -n hw.logicalcpu)
else
  CORES=$(nproc)
fi

./scripts/reformat.sh
CXX=$CXX make -j$CORES
./tests/run $BIN

lines=$(find $BIN -name "*.lines" | xargs cat | awk '{s+=$1} END {printf "%d\n", (s/1000)}')
echo "compilation mass: $lines kloc"
