#!/usr/bin/env bash
set -euo pipefail

readonly BIN=$1
readonly scriptDir=$(dirname $0)

readonly tmpDir=/tmp/test-cw-$$
trap "rm -rf $tmpDir" EXIT
mkdir -p "$tmpDir"

function main
{
  run_test real_mp4_aac
  run_test real_mp4_avc
  run_test real_mp4_heif

  run_test check_rules_folder_isobmff isobmff mp4
  run_test check_rules_folder_isobmff heif mp4
  run_test check_rules_folder_isobmff miaf hif
  run_test check_rules_folder_isobmff avif avif
  run_test check_rules_folder_isobmff av1hdr10plus mp4
  run_test check_rules_folder_raw av1hdr10plus obu
  run_test miaf_file_extension

  echo "OK"
}

function run_test
{
  echo "* $*"
  "$@"
}

function real_mp4_aac
{
  $BIN/cw.exe isobmff $scriptDir/aac.mp4 > $tmpDir/aac.new
  compare $scriptDir/aac.ref $tmpDir/aac.new
}

function real_mp4_avc
{
  $BIN/cw.exe isobmff $scriptDir/avc.mp4 > $tmpDir/avc.new
  compare $scriptDir/avc.ref $tmpDir/avc.new
}

function real_mp4_heif
{
  #generated with 'isoifftool -m 0 -t avc -i avc.264 -o heif.mp4 -s 320 240'
  $BIN/cw.exe heif $scriptDir/heif.mp4 > $tmpDir/heif.new  || true
  compare $scriptDir/heif.ref $tmpDir/heif.new

  $BIN/cw.exe miaf $scriptDir/heif.mp4 > $tmpDir/miaf.new  || true
  compare $scriptDir/miaf.ref $tmpDir/miaf.new
}

function miaf_file_extension
{
  cp $scriptDir/heif.mp4 $tmpDir/heif_no_ext
  $BIN/cw.exe miaf $tmpDir/heif_no_ext > $tmpDir/no_file_extension.new  || true
  compare $scriptDir/no_file_extension.ref $tmpDir/no_file_extension.new
}

function check_rules
{
  local spec="$1"
  local name="$2"
  local ext="$3"
  local filepath="$tmpDir/$name.$ext"
  mkdir -p $(dirname $filepath)

  if [[ $ext == "mp4" ]] ; then
    nasm $scriptDir/$name.asm -f bin -o $filepath
  else
    filepath=$scriptDir/$name.$ext
  fi

  if [[ $name == *invalid* ]] ; then
    $BIN/cw.exe $spec $filepath > $tmpDir/$name.new 2>&1  || true
  else
    $BIN/cw.exe $spec $filepath > $tmpDir/$name.new  || true
  fi

  compare $scriptDir/$name.ref $tmpDir/$name.new
}

function check_rules_folder_isobmff
{
  local folder="$1"
  for i in `ls $scriptDir/$folder/*.asm` ; do
    local name=`basename ${i%.*}`
    run_test check_rules $folder "$folder/$name" "$2"
  done
}

function check_rules_folder_raw
{
  local folder="$1"
  for i in `ls $scriptDir/$folder/*.$2` ; do
    local name=`basename ${i%.*}`
    run_test check_rules $folder "$folder/$name" "$2"
  done
}

function compare
{
  local ref=$1
  local new=$2

  # cp "$new" "$ref"
  diff -Naur "$ref" "$new"
}

main "$@"
