#!/usr/bin/env bash
set -euo pipefail

readonly BIN=$1
readonly scriptDir=$(dirname $0)

readonly tmpDir=/tmp/test-cw-$$
trap "rm -rf $tmpDir" EXIT
mkdir -p "$tmpDir"

function main
{
  $BIN/cw.exe dummy $scriptDir/aac.mp4 > $tmpDir/aac.new
  compare $scriptDir/aac.ref $tmpDir/aac.new

  check_rules dummy dummy_no_ftyp
  check_rules heif heif/valid
  check_rules heif heif/invalid-no-ftyp
  check_rules heif heif/invalid-no-mif1

  echo "OK"
}

function check_rules
{
  local spec="$1"
  local name="$2"
  local mp4path="$tmpDir/$name.mp4"
  mkdir -p $(dirname $mp4path)
  nasm $scriptDir/$name.asm -f bin -o $mp4path
  $BIN/cw.exe $spec $tmpDir/$name.mp4 > $tmpDir/$name.new
  compare $scriptDir/$name.ref $tmpDir/$name.new
}

function compare
{
  local ref=$1
  local new=$2

  # cp "$new" "$ref"
  diff -Naur "$ref" "$new"
}

main "$@"
