#pragma once

#include "core/box_reader.h"

#include <cstdint>
#include <string>
#include <vector>

enum ObuType {
  OBU_IA_CODEC_CONFIG = 0,
  OBU_IA_AUDIO_ELEMENT = 1,
  OBU_IA_MIX_PRESENTATION = 2,
  OBU_IA_PARAMETER_BLOCK = 3,
  OBU_IA_TEMPORAL_DELIMITER = 4,
  OBU_IA_AUDIO_FRAME = 5,
  OBU_IA_AUDIO_FRAME_ID0 = 6,
  OBU_IA_AUDIO_FRAME_ID1 = 7,
  OBU_IA_AUDIO_FRAME_ID2 = 8,
  OBU_IA_AUDIO_FRAME_ID3 = 9,
  OBU_IA_AUDIO_FRAME_ID4 = 10,
  OBU_IA_AUDIO_FRAME_ID5 = 11,
  OBU_IA_AUDIO_FRAME_ID6 = 12,
  OBU_IA_AUDIO_FRAME_ID7 = 13,
  OBU_IA_AUDIO_FRAME_ID8 = 14,
  OBU_IA_AUDIO_FRAME_ID9 = 15,
  OBU_IA_AUDIO_FRAME_ID10 = 16,
  OBU_IA_AUDIO_FRAME_ID11 = 17,
  OBU_IA_AUDIO_FRAME_ID12 = 18,
  OBU_IA_AUDIO_FRAME_ID13 = 19,
  OBU_IA_AUDIO_FRAME_ID14 = 20,
  OBU_IA_AUDIO_FRAME_ID15 = 21,
  OBU_IA_AUDIO_FRAME_ID16 = 22,
  OBU_IA_AUDIO_FRAME_ID17 = 23,
  OBU_IA_METADATA = 24,
  OBU_IA_SEQUENCE_HEADER = 31,
};

struct IReader;

void parseIamfObus(IReader *br, int64_t size);
